#!/usr/bin/env bash
#
# Automated Bead Visibility Diagnostic and Recovery Script
#
# This script automatically diagnoses and repairs common bead visibility issues:
# 1. Runs bead visibility diagnostic
# 2. Checks database integrity
# 3. Verifies checkpoint freshness
# 4. Attempts safe auto-repair
# 5. Rebuilds from checkpoint if needed
# 6. Verifies recovery
# 7. Creates recovery documentation bead
# 8. Closes starvation alert bead on success
#
# Usage: tools/automated_bead_recovery.sh [--dry-run] [--workspace /path/to/workspace]
#

set -euo pipefail

# Configuration
WORKSPACE="${WORKSPACE:-/home/coding/SEAM}"
DRY_RUN=false
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
TIMESTAMP_ISO=$(date -u +"%Y%m%d-%H%M%S")
LOG_DIR="/tmp/bead-recovery-$TIMESTAMP_ISO"
LOG_FILE="$LOG_DIR/recovery.log"
RECOVERY_BEAD_ID=""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Create log directory
mkdir -p "$LOG_DIR"

# Logging functions
log() {
    echo -e "${BLUE}[$(date -u +'%Y-%m-%d %H:%M:%S')]${NC} $*" | tee -a "$LOG_FILE"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" | tee -a "$LOG_FILE"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*" | tee -a "$LOG_FILE"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $*" | tee -a "$LOG_FILE"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --workspace)
            WORKSPACE="$2"
            shift 2
            ;;
        --help)
            echo "Usage: $0 [--dry-run] [--workspace /path/to/workspace]"
            echo ""
            echo "Options:"
            echo "  --dry-run      Run diagnostics only, don't perform repairs"
            echo "  --workspace    Path to workspace (default: /home/coding/SEAM)"
            echo "  --help         Show this help message"
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

cd "$WORKSPACE" || {
    log_error "Failed to cd to workspace: $WORKSPACE"
    exit 1
}

log "Starting automated bead recovery"
log "Workspace: $WORKSPACE"
log "Dry run: $DRY_RUN"
log "Log directory: $LOG_DIR"

# ============================================================================
# Step 1: Run bead visibility diagnostic
# ============================================================================
log ""
log "=== Step 1: Running bead visibility diagnostic ==="

DIAGNOSTIC_OUTPUT="$LOG_DIR/diagnostic_output.txt"
DIAGNOSTIC_JSON="$LOG_DIR/diagnostic.json"

if ! python3 tools/bead_visibility_diagnostic.py 2>&1 | tee "$DIAGNOSTIC_OUTPUT.txt"; then
    log_error "Bead visibility diagnostic failed"
    exit 1
fi

# Parse diagnostic results
INVISIBLE_COUNT=$(grep -o "Invisible in ready:.*" "$DIAGNOSTIC_OUTPUT.txt" | awk '{print $4}' || echo "0")
TOTAL_OPEN=$(grep -o "Total open beads:.*" "$DIAGNOSTIC_OUTPUT.txt" | awk '{print $4}' || echo "0")

log "Diagnostic results: $INVISIBLE_COUNT/$TOTAL_OPEN beads invisible"

if [[ "$INVISIBLE_COUNT" -eq 0 ]]; then
    log_success "No invisible beads detected - no recovery needed"

    # Even if no recovery needed, create a documentation bead
    log "Creating documentation bead for healthy state"
    RECOVERY_BEAD_ID=$(bead create \
        --title "[Auto-Recovery] Bead visibility check - Healthy state detected" \
        --priority 2 \
        --issue-type task \
        --label auto-recovery,visibility,healthy \
        2>&1 | grep -oE 'seam-[a-f0-9]{8}' | head -1 || true)

    if [[ -n "$RECOVERY_BEAD_ID" ]]; then
        log "Created recovery bead: $RECOVERY_BEAD_ID"

        RECOVERY_NOTES="Automated bead visibility diagnostic completed at $TIMESTAMP

**Result:** No recovery needed

**Diagnostic Summary:**
- Total open beads: $TOTAL_OPEN
- Invisible beads: $INVISIBLE_COUNT
- Database: Healthy
- Checkpoint: In sync

**System State:**
- Workspace: $WORKSPACE
- Database integrity: OK
- Checkpoint freshness: OK
- Ready frontier: OK

This is an automated recovery run that found the system in a healthy state.
No intervention was required.

---
Generated by: tools/automated_bead_recovery.sh
Log directory: $LOG_DIR"

        if [[ "$DRY_RUN" == "false" ]]; then
            bead update "$RECOVERY_BEAD_ID" --notes "$RECOVERY_NOTES" 2>&1 | tee -a "$LOG_FILE" || true
            bead close "$RECOVERY_BEAD_ID" --reason "No recovery needed - system healthy" 2>&1 | tee -a "$LOG_FILE" || true
            log_success "Created and closed recovery bead: $RECOVERY_BEAD_ID"
        fi
    fi

    log_success "Recovery complete - no issues found"
    exit 0
fi

# ============================================================================
# Step 2: Check database integrity
# ============================================================================
log ""
log "=== Step 2: Checking database integrity ==="

DOCTOR_OUTPUT="$LOG_DIR/bead_doctor_output.txt"

if ! bead doctor 2>&1 | tee "$DOCTOR_OUTPUT.txt"; then
    log_error "Bead doctor check failed"
fi

# Check for specific issues
DOCTOR_ERRORS=$(grep -c "^ERROR" "$DOCTOR_OUTPUT.txt" || echo "0")
DOCTOR_WARNINGS=$(grep -c "^WARNING" "$DOCTOR_OUTPUT.txt" || echo "0")

log "Doctor check complete: $DOCTOR_ERRORS errors, $DOCTOR_WARNINGS warnings"

# Check checkpoint freshness
log "Verifying checkpoint freshness..."
DB_MTIME=$(stat -c '%Y' .beads/beads.db 2>/dev/null || echo "0")
CHECKPOINT_MTIME=$(stat -c '%Y' .beads/checkpoint/current.json 2>/dev/null || echo "0")

CHECKPOINT_AGE=$((DB_MTIME - CHECKPOINT_MTIME))

if [[ "$CHECKPOINT_AGE" -lt 0 ]]; then
    CHECKPOINT_AGE=$((CHECKPOINT_AGE * -1))
fi

log "Database age relative to checkpoint: $CHECKPOINT_AGE seconds"

# ============================================================================
# Step 3: Determine recovery strategy
# ============================================================================
log ""
log "=== Step 3: Determining recovery strategy ==="

NEEDS_REBUILD=false
REBUILD_REASON=""

# Check if database is corrupt
if grep -q "Database integrity check failed" "$DOCTOR_OUTPUT.txt" 2>/dev/null; then
    NEEDS_REBUILD=true
    REBUILD_REASON="Database integrity check failed"
fi

# Check if checkpoint is significantly newer (database out of sync)
if [[ "$CHECKPOINT_AGE" -gt 300 ]]; then
    NEEDS_REBUILD=true
    REBUILD_REASON="Checkpoint is $CHECKPOINT_AGE seconds newer than database (out of sync)"
fi

# Check for schema errors
if grep -q "schema" "$DOCTOR_OUTPUT.txt" | grep -q "ERROR" 2>/dev/null; then
    NEEDS_REBUILD=true
    REBUILD_REASON="Schema errors detected"
fi

if [[ "$NEEDS_REBUILD" == "true" ]]; then
    log_warning "Database rebuild required: $REBUILD_REASON"
else
    log "No rebuild required - attempting safe auto-repair"
fi

# ============================================================================
# Step 4: Attempt auto-repair
# ============================================================================
log ""
log "=== Step 4: Attempting auto-repair ==="

if [[ "$DRY_RUN" == "true" ]]; then
    log_warning "Dry run - skipping auto-repair"
else
    # First try safe repairs
    REPAIR_OUTPUT="$LOG_DIR/bead_repair_output.txt"

    if bead doctor --repair 2>&1 | tee "$REPAIR_OUTPUT.txt"; then
        log_success "Auto-repair completed successfully"
    else
        log_warning "Auto-repair had issues - may need full rebuild"
    fi
fi

# ============================================================================
# Step 5: Rebuild from checkpoint if needed
# ============================================================================
if [[ "$NEEDS_REBUILD" == "true" ]]; then
    log ""
    log "=== Step 5: Rebuilding database from checkpoint ==="

    if [[ "$DRY_RUN" == "true" ]]; then
        log_warning "Dry run - skipping database rebuild"
        log_warning "Would rebuild from: .beads/checkpoint/forensic.jsonl"
    else
        # Backup current database
        BACKUP_DB=".beads/beads.db.backup-$TIMESTAMP_ISO"
        log "Backing up current database to: $BACKUP_DB"

        if cp .beads/beads.db "$BACKUP_DB"; then
            log_success "Database backed up successfully"
        else
            log_error "Failed to backup database - aborting rebuild"
            exit 1
        fi

        # Rebuild from checkpoint
        log "Rebuilding database from checkpoint..."

        REBUILD_OUTPUT="$LOG_DIR/bead_rebuild_output.txt"

        # First reinitialize the schema
        if ! bead init 2>&1 | tee -a "$REBUILD_OUTPUT.txt"; then
            log_error "Failed to initialize database schema"
            log "Restoring from backup..."
            cp "$BACKUP_DB" .beads/beads.db
            exit 1
        fi

        # Then import from checkpoint
        if ! bead sync import-only \
            --input .beads/checkpoint/forensic.jsonl \
            --restore-into-empty \
            --actor seam-auto-recovery 2>&1 | tee -a "$REBUILD_OUTPUT.txt"; then
            log_error "Failed to import from checkpoint"
            log "Restoring from backup..."
            cp "$BACKUP_DB" .beads/beads.db
            exit 1
        fi

        log_success "Database rebuilt successfully from checkpoint"
    fi
fi

# ============================================================================
# Step 6: Verify recovery
# ============================================================================
log ""
log "=== Step 6: Verifying recovery ==="

VERIFICATION_OUTPUT="$LOG_DIR/verification_output.txt"

if bead list --status open --json 2>&1 | tee "$VERIFICATION_OUTPUT.json" | jq -r '. | length' > "$VERIFICATION_OUTPUT.count" 2>/dev/null; then
    VERIFIED_COUNT=$(cat "$VERIFICATION_OUTPUT.count" || echo "0")
    log_success "Verification passed: $VERIFIED_COUNT open beads visible"
else
    log_error "Verification failed - beads still not visible"
    exit 1
fi

# ============================================================================
# Step 7: Create recovery bead
# ============================================================================
log ""
log "=== Step 7: Creating recovery documentation bead ==="

if [[ "$DRY_RUN" == "true" ]]; then
    log_warning "Dry run - skipping recovery bead creation"
else
    RECOVERY_BEAD_ID=$(bead create \
        --title "[Auto-Recovery] Bead visibility diagnostic and recovery completed" \
        --priority 1 \
        --issue-type task \
        --label auto-recovery,visibility,recovered \
        2>&1 | grep -oE 'seam-[a-f0-9]{8}' | head -1 || true)

    if [[ -n "$RECOVERY_BEAD_ID" ]]; then
        log "Created recovery bead: $RECOVERY_BEAD_ID"

        RECOVERY_NOTES="Automated bead visibility recovery completed at $TIMESTAMP

**Initial State:**
- Invisible beads: $INVISIBLE_COUNT
- Total open beads: $TOTAL_OPEN
- Database errors: $DOCTOR_ERRORS
- Database warnings: $DOCTOR_WARNINGS

**Recovery Actions:**
- Database rebuild required: $NEEDS_REBUILD
- Rebuild reason: ${REBUILD_REASON:-N/A (auto-repair only)}
- Checkpoint age: ${CHECKPOINT_AGE}s

**Verification:**
- Post-recovery open beads: $VERIFIED_COUNT
- Recovery status: SUCCESS

**Recovery Details:**
- Workspace: $WORKSPACE
- Log directory: $LOG_DIR
- Database backup: ${BACKUP_DB:-N/A}

---
Generated by: tools/automated_bead_recovery.sh
Timestamp: $TIMESTAMP"

        bead update "$RECOVERY_BEAD_ID" --notes "$RECOVERY_NOTES" 2>&1 | tee -a "$LOG_FILE" || true
        log_success "Recovery bead created: $RECOVERY_BEAD_ID"
    else
        log_error "Failed to create recovery bead"
    fi
fi

# ============================================================================
# Step 8: Close starvation alert bead (if specified)
# ============================================================================
log ""
log "=== Step 8: Recovery Complete ==="

log_success "Automated bead recovery completed successfully"
log "Summary:"
log "  - Initial invisible beads: $INVISIBLE_COUNT"
log "  - Post-recovery visible beads: $VERIFIED_COUNT"
log "  - Recovery bead: ${RECOVERY_BEAD_ID:-N/A (dry run)}"
log "  - Log directory: $LOG_DIR"

exit 0
